### ISSUE TITLE
Support `codecov-action@v4` breaking changes

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/wg-frontend#177]
[From slack](https://openedx.slack.com/archives/C04BM6YC7A6/p1711620349847079):
> Hi team, we noticed that Codecov has stopped working in frontend-app-authn recently. It seems like it can't find the token.
Does anyone have any idea on how to resolve this?

This happened because https://github.com/openedx/frontend-app-authn/pull/1172 was merged which bumped the codecov action from v3 to v4 without accounting for the [breaking changes](https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes)
> Tokenless uploading is unsupported

We use the codecov workflow in quite a few places throughout the org https://github.com/search?q=org%3Aopenedx+uses%3A+codecov%2Fcodecov-action&type=code and I expect dependabot PRs to start making it into a bunch of those repos.

If we want to move to the v4 version of the action we should ensure we make the required changes to support it
* Add a codecov token as an org secret
* Update workflows from
  ```yml
      - name: Run Code Coverage
        uses: codecov/codecov-action@v4
  ``` 
  to
  ```yml
      - name: Run Code Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
  ```
